"""
Golden-master tests for node_world_matrix().

Each scene CSV in tests/golden/scenes/ is tested independently:
  - Load the scene.
  - Compute node_world_matrix() for every node.
  - Compare against the expected matrices stored in tests/golden/expected/<scene>.json.

Expected matrices are generated by generate_expected.py (Python baseline until
the ANTz C oracle is available).  Run that script first, then run pytest.

Phase A: once the C oracle is built, rerun generate_expected.py with --oracle
to replace the baseline with ANTz-computed reference matrices, making these
tests verify conformance against the ground truth.
"""

import pytest

from glyphviz_core.scene import Scene, node_world_matrix

from .conftest import (
    SCENE_DIR,
    all_scene_names,
    assert_matrix_close,
    load_oracle,
)

BASE_SCALE = 3.0  # must match generate_expected.py


@pytest.mark.parametrize("scene_name", all_scene_names())
def test_world_matrices(scene_name: str):
    """node_world_matrix() matches the stored expected matrices for every node."""
    scene = Scene.load(SCENE_DIR / f"{scene_name}.csv", base_scale=BASE_SCALE)
    expected = load_oracle(scene_name)

    for node in scene.nodes:
        if node.id not in expected:
            pytest.fail(f"Node {node.id} missing from oracle for scene '{scene_name}'")
        M = node_world_matrix(node, scene)
        assert_matrix_close(M, expected[node.id], node.id)


@pytest.mark.parametrize("scene_name", all_scene_names())
def test_last_row_is_homogeneous(scene_name: str):
    """Last row of every world matrix must be [0, 0, 0, 1]."""
    scene = Scene.load(SCENE_DIR / f"{scene_name}.csv", base_scale=BASE_SCALE)
    for node in scene.nodes:
        M = node_world_matrix(node, scene)
        assert M[3, 0] == 0.0
        assert M[3, 1] == 0.0
        assert M[3, 2] == 0.0
        assert M[3, 3] == 1.0, f"Node {node.id}: M[3,3] = {M[3,3]}"


@pytest.mark.parametrize("scene_name", all_scene_names())
def test_rotation_part_is_orthonormal(scene_name: str):
    """The de-scaled 3x3 block is orthonormal when the parent has uniform scale.

    With a non-uniform parent scale the ANTz-correct rendering matrix is
        R_parent @ S_parent @ R_child_local @ S_child
    which introduces genuine shear into the world matrix (a child oriented 45°
    to a stretched parent becomes a diamond shape — exactly what ANTz does).
    Asserting RᵀR ≈ I is only valid when the parent scale is isotropic, so
    this test skips non-uniform-parent nodes rather than flagging them as bugs.
    """
    import numpy as np

    scene = Scene.load(SCENE_DIR / f"{scene_name}.csv", base_scale=BASE_SCALE)
    by_id = {n.id: n for n in scene.nodes}

    for node in scene.nodes:
        # Skip nodes whose parent has non-uniform world scale — those intentionally
        # produce shear and do not have an orthonormal de-scaled rotation block.
        parent = by_id.get(node.parent_id)
        if parent is not None and parent is not node:
            pw = scene.world_scale(parent.id) or (1.0, 1.0, 1.0)
            if not (abs(pw[0] - pw[1]) < 1e-9 and abs(pw[1] - pw[2]) < 1e-9):
                continue  # non-uniform parent scale → shear is expected

        M = node_world_matrix(node, scene)
        cols = M[:3, :3]
        col_norms = [float(np.linalg.norm(cols[:, i])) for i in range(3)]
        for norm in col_norms:
            assert norm > 0, f"Node {node.id}: zero-length column in world matrix"
        R = cols / col_norms   # de-scaled rotation
        RtR = R.T @ R
        np.testing.assert_allclose(
            RtR, np.eye(3), atol=1e-6,
            err_msg=f"Node {node.id}: rotation sub-matrix is not orthonormal\n{R}",
        )
